package:
  name: q2-fastp
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel

  build:
    - python {{ python }}
    - setuptools
    - versioningit

  run:
    - fastp
    - multiqc
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - q2templates >={{ q2templates }}

test:
  requires:
    - parameterized
    - pytest-xdist
  imports:
    - q2_fastp
    - qiime2.plugins.fastp
  commands:
    - pytest --pyargs q2_fastp -n 4

about:
  home: https://github.com/bokulich-lab/q2-fastp
  license: BSD-3-Clause
  license_family: BSD
