{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-fastp
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - fastp
    - multiqc
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - parameterized
  imports:
    - q2_fastp
    - qiime2.plugins.fastp
  commands:
    - coverage run --rcfile ./repo/.coveragerc -m pytest && coverage xml -o coverage.xml

about:
  home: https://github.com/bokulich-lab/q2-fastp
  license: BSD-3-Clause
  license_family: BSD
